#!/bin/bash

# Copyright 2018 Alexander Majka / JEFF Media GbR
# www.jeff-media.de
# Version 1.0

# THIS SCRIPT HAS TO BE PLACED IN THE ROOT OF THE IPHONE/IPAD BACKUP DIRECTORY
# It will search through all the files and copy all images and videos
# Please change the location where the files should be saved
target="/tmp/iphone-restore"

if [[ "$1" == "-f" ]]; then
	force=1
	shift
else
	force=0
fi

set -e

shopt -s nullglob

#max=100
current=0

mkdir -p "$target"

function is_jpg() {
	type="$@"
	count=$(echo $type | grep -i "JPEG image data" | wc -l)
	if [[ "$count" -eq 1 ]]; then
		echo 1
	else
		echo 0
	fi
}

function is_mov() {
	type="$@"
	count=$(echo $type | grep -i "Apple QuickTime movie" | wc -l)
	if [[ "$count" -eq 1 ]]; then
		echo 1
	else
		echo 0
	fi
}

function is_png() {
	type="$@"
	count=$(echo $type | grep -i "PNG image data" | wc -l)
	if [[ "$count" -eq 1 ]]; then
		echo 1
	else
		echo 0
	fi
}

function is_mp4() {
	type="$@"
	count=$(echo $type | grep -i "MP4" | wc -l)
	if [[ "$count" -eq 1 ]]; then
		echo 1
	else
		echo 0
	fi
}

function is_heif() {
	type="$@"
	count=$(echo $type | grep -i "HEIF image" | wc -l)
	if [[ "$count" -eq 1 ]]; then
		echo 1
	else
		echo 0
	fi
}

function cp_if_different() {
	ext="$1"
	shift
	file="$@"
	cmp --silent $file "$target"/"$file"."$ext" && echo "   $file has already been saved" || cp -i $file "$target"/"$file"."$ext"
}

for dir in */; do

	cd "$dir"
	echo "working with directory $dir"
	
	for subdir in */; do
		echo " working with subdirectory $subdir"
		cd "$subdir"
		if [[ -f ".iphone-backup-extractor" && "$force" -eq 0 ]]; then
			echo "subdirectory $subdir has already been saved completely."
			continue
		fi
		for file in *; do
			current=$((current+1))
			echo "  processing file number $current ($file)"
			#[[ "$current" -gt "$max" ]] && exit
			type=$(file "$file" | cut -d ":" -f2)
			if [[ "$(is_mov $type)" -eq 1 ]]; then
				echo "   $file is a quicktime movie"
				cp_if_different MOV "$file"
			elif [[ "$(is_jpg $type)" -eq 1 ]]; then
				echo "   $file is a jpeg image"
				cp_if_different JPG "$file"
			elif [[ "$(is_png $type)" -eq 1 ]]; then
				echo "   $file is a png image"
				cp_if_different PNG "$file"
			elif [[ "$(is_heif $type)" -eq 1 ]]; then
				echo "   $file is a heif image"
				cp_if_different HEIF "$file"
			elif [[ "$(is_mp4 $type)" -eq 1 ]]; then
				echo "   $file is a mp4 movie"
				cp_if_different MP4 "$file"				
			else
				echo "   $file has unknown type ($type )"
			fi
			echo
		done
		if [[ "$force" -eq 0 ]]; then
			date > .iphone-backup-extractor
		fi
		cd ..
	done
	
	cd ..
done
